### PR TITLE
Update __init__.py

### PR DESCRIPTION
**Pull request by ghost**
add specific encoding='utf-8'  to open file

### CODE REVIEW

**Comment by tumb1er** [comment]
```
  File "tests.py", line 84, in testOpenCoverage
    self.c.open(self.filename)
  File "/home/travis/build/tumb1er/coverage2clover/clover/__init__.py", line 156, in open
    c.count_loc(sources)
  File "/home/travis/build/tumb1er/coverage2clover/clover/__init__.py", line 87, in count_loc
    with open(filename, encoding='utf-8') as f:
TypeError: 'encoding' is an invalid keyword argument for this function
```
Please, add python-2.7 support.

**Comment by ghost** [comment]
opened a new PR

**Comment by tumb1er** [comment]
Thanks!

**Comment by ghost** [comment]
any chance you can release a new version to pypi?

**Pull request merged**
