### PR TITLE
Formatting changes - Formatted Code using Black

### PR DESCRIPTION
**Pull request by gauravojha**
**Changes being merged**
- Formatted code using `black`. Information here: https://github.com/psf/black
- Used black==20.8b1

### CODE REVIEW

**Comment by gauravojha** [comment]
**Note:** python3.4 tests are failing in `pygount`. Need to check version of pygount being used. Error thrown:

```
File "/home/travis/virtualenv/python3.4.8/lib/python3.4/site-packages/coverage2clover-2.0.1-py3.4.egg/clover/__init__.py", line 7, in <module>
  File "/home/travis/virtualenv/python3.4.8/lib/python3.4/site-packages/pygount-1.2.4-py3.4.egg/pygount/__init__.py", line 6, in <module>
    from .analysis import encoding_for, DuplicatePool, SourceAnalysis, SourceScanner, SourceState, source_analysis
  File "/home/travis/virtualenv/python3.4.8/lib/python3.4/site-packages/pygount-1.2.4-py3.4.egg/pygount/analysis.py", line 15, in <module>
    from typing import Dict, Generator, List, Optional, Pattern, Sequence, Set, Tuple, Union
ImportError: No module named 'typing'
```

Python 3.4 is EOL. Probably best to remove it.

**Comment by gauravojha** [comment]
@tumb1er  please review when you get a chance. 

Once the 2 open PRs are merged, will send another PR to bring in the version upgrades for `coverage`, deprecating EOL Python3.4 and adding support for Python3.8

**Review by tumb1er — APPROVED** [review]

**Comment by tumb1er** [comment]
> Python 3.4 is EOL. Probably best to remove it.

I'll merge this PR as soon as python-3.4 will be excluded from test matrix.

**Comment by gauravojha** [comment]
@tumb1er please don't merge this yet.

Once the python3.4 matrix goes in, will update the `setup.py` to reflect proper python versions.

**Comment by tumb1er** [comment]
> Once the python3.4 matrix goes in, will update the setup.py to reflect proper python versions.

I'll do this while preparing new release version for PyPI.

**Comment by tumb1er** [comment]
Please rebase to test against python-3.8

**Comment by gauravojha** [comment]
> > Once the python3.4 matrix goes in, will update the setup.py to reflect proper python versions.
> 
> I'll do this while preparing new release version for PyPI.

Got it.  Thanks..

One more question our of curiosity. Once I send a PR updating version for `coverage`, will you create a new version 3.0.1 at that point?

**Comment by tumb1er** [comment]
Why not 3.0.0?

**Comment by gauravojha** [comment]
oh nvm. my bad, I didn't see 3.0.0 as the milestone. I thought the commit at that point was tagged..

**Comment by gauravojha** [comment]
@tumb1er  I rebased on my fork, and I think I made a mistake during the rebase/merge somewhere. Don't want your commit history to be polluted. Let me send a fresh PR? (Travis CI is passing with python 3.8 though)

**Comment by tumb1er** [comment]
If you wish, you may send a new PR or just force-push your branch with corrected history.

**Comment by gauravojha** [comment]
Thanks, I just sent a new PR. Here you are @tumb1er  #29

**Pull request closed without merging**
